name: Microservices Build docker hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # Construccion de jars
      - name: Build Micro Client
        run: mvn -f MicroservicioWorker/pom.xml clean install -DskipTests=true
      
      - name: Build Micro Item
        run: mvn -f MicroservicioArticulo/pom.xml clean install -DskipTests=true

      - name: Build Micro Config
        run: mvn -f MicroservicioConfig/pom.xml clean install -DskipTests=true

      - name: Build Micro Eureka
        run: mvn -f MicroservicioEureka/pom.xml clean install -DskipTests=true


      # Construccion de imagenes
      - name: Build image Worker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes:worker .
        working-directory: MicroservicioeWorker
        
      - name: Build image config
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes:config .
        working-directory: MicroservicioConfig
        
      - name: Build image eureka
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes:eureka .
        working-directory: MicroservicioEureka

      - name: Build image articulo
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes:articulo .
        working-directory: MicroservicioArticulo


      #Login docker
      - name: Log in to Docker Hub 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


        
      #Envio de imagenes a docker hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mes:client
          docker push ${{ secrets.DOCKER_USERNAME }}/mes:config
          docker push ${{ secrets.DOCKER_USERNAME }}/mes:eureka
          docker push ${{ secrets.DOCKER_USERNAME }}/mes:item
